"""add embedding to document_chunks

Revision ID: 5ff358eadabf
Revises: 8df03601a00b
Create Date: 2026-03-12 20:43:02.001261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff358eadabf'
down_revision: Union[str, Sequence[str], None] = '8df03601a00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding', sa.JSON(), nullable=True))
    op.drop_column('document_chunks', 'collection_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('collection_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
